# Generated by Django 2.0.3 on 2018-04-01 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180401_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='label',
            new_name='tags',
        ),
    ]
