# Generated by Django 2.0.3 on 2018-04-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20180402_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organiser',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.SlugField(max_length=32),
        ),
    ]
